

build:
	mpic++ 1Task.cpp -o program.o
run:
	# mpic++ 1Task.cpp -o program.o
	# mpic++ 2Task.cpp -o program.o
	# mpic++ 3Task.cpp -o program.o
	mpic++ 4Task.cpp -o program.o
	time mpirun -n 4 program.o
