##
# Project Title
#
# @file
# @version 0.1

build:
	g++ -fopenmp lab1.cpp -o output
run:
	g++ -fopenmp lab1.cpp -o output
	./output
rundebug:
	g++ -fopenmp lab1.cpp -o output
# 	g++  lab1.cpp -o output
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./output >> responses.txt
	./check_if_deterministic.sh
runbenchmark:
	g++-12 -fopenmp lab1.cpp -o output
# 	g++-12  lab1.cpp -o output
	./output
	./output 
	./output 
# end
